### ISSUE TITLE
checkApprovalSync is recommended in documentation but is not exported from sdk

### ISSUE THREAD

**Issue by krisbitney** [rango-exchange/rango-sdk#14]
Needs an export statement here: https://github.com/rango-exchange/rango-sdk/blob/master/packages/rango-sdk-basic/src/services/executor.ts#L42

**Comment by RanGojo** [comment]
Sorry for delay, please check our evm example for more details. We have some changes there regarding your question.
https://github.com/rango-exchange/rango-sdk/tree/master/examples/basic/node-evm.
